### PR TITLE
Ember App Upgrade and Time Series Data

### PR DESCRIPTION
**Pull request by mansona**
Hey All, 

This PR is incomplete and serves 2 purposes: a) Remove the need for Grunt by upgrading the ember-cli to the latest version (and starting to us pods) and b) to implement a time series graph for when a job either completes or fails.

I'm opening this PR early to start a discussion on the structural change that i've done to the ember app. When I first looked at the kue-ui I dismissed the idea of being able to extend it because I _didn't know that it was just an ember app_. Essentially I didn't know that the grunt file and the express app were just really small wrappers over the ember app. I would imagine that I'm not the only one that has felt this way so that's why I am proposing that we ditch the grunt wrapper because of the major progress that Ember-Cli has made recently. 

The second half of this PR is to implement the time series graph https://cloudup.com/cc_pxT9qOgZ which is mostly working but depends on this PR before it is a possibility: https://github.com/Automattic/kue/pull/794 

Anyway, let me know what you think about the restructuring of the app. I would love to conclude that discussion before I progress much further on my "actual feature" that I'm working on so that if necessary I can just undo the restructuring work that I've done here. 

Thanks :+1:

### CODE REVIEW

**Comment by mansona** [comment]
Right so I think i'm finished here. I've made a short video of what the new route looks like: 

[kue-ui demo](http://www.youtube.com/watch?v=MLy5oz6ZKrc)

This is also now using ember-data for both the `state-timebucket` and `job` **models**. So that ember-data didn't trip over itself I renamed what used to be `models/job.js` to `models/job-non-model.js` and updated all references to it. If my PRs to Kue get merged it might be worth coming up with a migration plan to move the whole UI over to ember data but that's really up to you :+1: 

Let me know what you think :smile:

**Comment by gabrielcsapo** [comment]
Is this being actively looked at?

**Comment by mansona** [comment]
@gabrielcsapo I have been using this in a live environment for quite some time now. I would imagine that this PR should wait until the required API endpoints are merged in the kue project: https://github.com/Automattic/kue/pull/794 

I don't see any other way to progress, have any ideas?

**Comment by gabrielcsapo** [comment]
Is there someone who has merge permissions?

**Comment by mansona** [comment]
@gabrielcsapo do you mean on Automattic/kue or here? I don't know anyone in Automattic personally but I trust that @behrad will get around to reviewing that PR soon, we just need a bit of patience 😄 

If you want to make use of this PR before that I can show you how to run from the branch on both repos if you are interested?

**Comment by mahnunchik** [comment]
Hi all! Any news?

**Comment by mansona** [comment]
Unfortunately no... I guess the folks at Automattic are super busy right now or focusing on something else at the moment but there has been no movement on the PR on that side. 

The previous maintainer of kue-ui said he would try and intro me to some people he knows at Automattic to get a conversation going about this so I'll let you know when I make any progress 👍

**Comment by k1ng440** [comment]
Please fix the name on package.json

**Comment by mansona** [comment]
Ok Just an update for anyone following this PR, I am closing this in favour of: https://github.com/stonecircle/kue-ui/pull/37 which will contain most of this work but will *disable* the time-series data feature. I will create another PR that reinstates it in a bit. 

#37 is part of a process of making this repo "just an ember app" and migrates the NodeJS Express part of this implementation into its own repo: https://github.com/stonecircle/kue-ui-express

Please let me know if you have any questions 👍

**Comment by jufemaiz** [comment]
@mansona just wondering if there was any movement on the time series JSON:API solution?

**Pull request closed without merging**
